<template>
  <LegalPage title="Conditions générales de vente">
    <p class="font-mono text-xs text-brand-mid">CONDITIONS GÉNÉRALES DE VENTE ET DE PRESTATIONS DE SERVICES Version du 02/07/2026 S.A.S PYROVIGIL</p>
    <h2>Préambule</h2>
      <p>Les présentes conditions générales concernent la S.A.S PYROVIGIL, Société par Actions Simplifiée au capital de                   1 000,00 €, ayant son siège social 49, rue des Tournesols, 83260 La Crau, immatriculée au Registre du Commerce et des Sociétés de Toulon sous le n° 2024 B 00791, n° SIREN 987 658 853, n° SIRET 987 658 853 00013,                                                      n° de TVA intracommunautaire FR21 987 658 853.</p>
      <p>La S.A.S PYROVIGIL est également enregistrée comme organisme de formation (déclaration d'activité n° 93830807483 auprès de la DREETS PACA, ne valant pas agrément de l'État).</p>
      <p>Au titre de cette seule activité de formation, la S.A.S PYROVIGIL est certifiée Qualiopi (certificat I.Cert n° CPS RNCQ 7259, délivré le 10 juin 2026 et valable jusqu'au 9 juin 2029). La certification qualité a été délivrée au titre de la catégorie d'action suivante : actions de formation. Cette certification porte exclusivement sur les actions de formation et ne s'étend pas aux autres prestations du Prestataire (conseil, maîtrise d'œuvre, applications de cartographie, servitudes DFCI).</p>
      <p>La S.A.S PYROVIGIL est représentée par Madame Diana Jeannot en qualité de Présidente.</p>
      <p>Le présent contrat, qui représente les conditions générales de vente et de prestations de services, est indivisible : l'ensemble des présentes clauses, les annexes, devis et préambule constituent un tout</p>
    <h2>Article 1 – Définitions</h2>
      <p>« Prestataire » : la S.A.S PYROVIGIL.</p>
      <p>« Client » : toute personne physique ou morale (particulier, professionnel, entreprise, association, collectivité ou administration) passant commande d'une Prestation auprès du Prestataire.</p>
      <p>« Consommateur » : tout Client personne physique agissant à des fins n'entrant pas dans le cadre de son activité commerciale, industrielle, artisanale, libérale ou agricole.</p>
      <p>« Prestation » : toute prestation de conseil, étude, maîtrise d'œuvre, formation, ou tout service ou produit numérique commercialisé par le Prestataire.</p>
      <p>« OLD » : Obligations Légales de Débroussaillement au sens des articles L.131-1 et suivants du Code forestier et des textes pris pour leur application.</p>
      <p>« Application » : tout outil de cartographie en ligne (web mapping) édité et mis à disposition par le Prestataire.</p>
      <p>« Module de gestion des OLD » : l'outil logiciel de suivi des contrôles et constats de terrain permettant l'édition automatisée de courriers adressés aux propriétaires concernés, dans les conditions et limites définies à l'article 11. À la différence des Applications, le Module traite des données à caractère personnel, strictement limitées au nom et à l'adresse postale des propriétaires.</p>
    <h2>Article 2 – Nature et catégories d'activités</h2>
      <p>La S.A.S PYROVIGIL a pour objet d'informer et de conseiller objectivement sur le risque de feu de forêt, en toute indépendance et sans lien avec aucun tiers. À ce titre, le Prestataire propose les catégories de Prestations suivantes :</p>
      <ul>
        <li>a) Conseil et études techniques – prestations de conseil, diagnostics et études techniques de mise en sécurité et de résilience des personnes et des biens face aux incendies de forêt : études d'aléa, de vulnérabilité et de « Défendabilité » ; études des voies d'accès et de desserte (PAC) ; études de défense extérieure contre l'incendie (DECI), hydrants et points d'eau ; plans communaux de gestion des OLD avec cartographie du zonage réglementaire ; accompagnement opérationnel et technique. Ces prestations sont précisées à l'article 12.</li>
        <li>b) Maîtrise d'œuvre (MOE) de travaux OLD – mission intellectuelle de conception, d'étude et d'assistance, sans réalisation de travaux, dans le périmètre strict défini à l'article 8.</li>
        <li>c) Applications de cartographie web (web mapping) – outils en ligne de détermination des zonages réglementaires d'OLD, dans les conditions et limites définies à l'article 10 ; le module de gestion des OLD et d'édition de courriers aux propriétaires relève en outre de l'article 11.</li>
        <li>d) Formation – actions de formation professionnelle non continue des adultes, régies en outre par le règlement intérieur de formation et, le cas échéant, par les conditions particulières des conventions ou contrats de formation.</li>
        <li>e) Servitudes DFCI – études et établissement des dossiers techniques et cartographiques relatifs aux servitudes de passage et d'aménagement de Défense des Forêts Contre l'Incendie (identification et caractérisation des ouvrages, définition des emprises, de la bande de roulement et des aires de retournement, de croisement et de contournement), dans les conditions définies à l'article 9.</li>
      </ul>
    <h2>Article 3 – Champ d'application</h2>
      <p>Les présentes Conditions Générales de Vente (« CGV ») sont seules applicables à toute commande de Prestation commercialisée par le Prestataire. Toute commande de Prestation validée par signature du bon de commande, de la proposition commerciale ou du devis par le Client entraîne l'acceptation sans réserve des présentes CGV ainsi que des éventuelles clauses particulières.</p>
      <p>Le Client reconnaît avoir pris connaissance, au moment de la signature du devis, du contrat ou du bon de commande, des CGV qui prévalent sur d'éventuelles conditions générales d'achat du Client, sauf accord exprès écrit du Prestataire. Aucune annotation manuscrite du Client sur un document contractuel n'aura de valeur entre les parties sauf accord écrit du Prestataire sur ladite modification. En l'absence de contrat signé négocié entre les parties, les présentes dispositions s'appliquent à toutes les Prestations vendues par le Prestataire.</p>
    <h2>Article 4 – Devis, contrat et bon pour commande</h2>
      <p>La Prestation n'est conclue qu'à compter de la confirmation du devis, du contrat ou du bon de commande. Le Prestataire se réserve le droit d'annuler ou de suspendre tout contrat ou commande d'un Client avec lequel existerait un litige relatif au paiement d'une facture antérieure. Les informations fournies par le Client lors de la commande l'engagent ; en cas d'erreur dans les éléments communiqués, le Prestataire ne saurait être tenu responsable. Le Prestataire prend en compte les besoins et demandes du Client afin de les concilier avec les enjeux et réglementations en vigueur.</p>
    <h2>Article 5 – Droit de rétractation (Consommateurs)</h2>
      <p>Le Client consommateur qui conclut le contrat à distance ou hors établissement dispose d'un droit de rétractation de quatorze jours à compter du lendemain de la conclusion du contrat. La rétractation s'effectue par toute déclaration dénuée d'ambiguïté adressée au Prestataire, notamment par courrier recommandé, par courrier électronique ou au moyen du formulaire figurant en annexe. Le Prestataire procède au remboursement dans un délai de quatorze jours à compter de la rétractation. Le droit de rétractation ne peut être exercé :</p>
      <ul>
        <li>pour les contrats de services pleinement exécutés avant la fin du délai de rétractation ;</li>
        <li>lorsque l'exécution a commencé, à la demande expresse du Client, avec sa reconnaissance de la perte de son droit de rétractation, et que la Prestation a été pleinement exécutée.</li>
      </ul>
      <p>En acceptant un devis de service avec paiement et demande d'exécution immédiate, le Client accepte la perte de son droit de rétractation si la Prestation a été pleinement exécutée avant sa demande de rétractation. Si le Client consommateur a demandé l'exécution immédiate de la Prestation puis exerce son droit de rétractation avant sa complète exécution, il est redevable du prix correspondant au service fourni jusqu'à la communication de sa décision de se rétracter, calculé au prorata du prix total convenu (article L.221-25 du Code de la consommation).</p>
    <h2>Article 6 – Délais d'exécution</h2>
      <p>Les délais d'exécution sont fournis à titre indicatif, en jours ouvrés, sur le devis. Si le Client renonce au délai de rétractation, la Prestation débute dès sa conclusion et dès lors que l'ensemble des pièces nécessaires a été fourni au Prestataire (au minimum un relevé de propriété, qui peut être une simple liste manuscrite des parcelles cadastrales bâties et non bâties, accompagnée des éventuelles servitudes connues). À défaut, le Client peut demander un devis pour l'obtention de ce relevé auprès de l'administration, conformément aux règles du livre des procédures fiscales.</p>
      <p>Entre professionnels, tout retard par rapport au délai indicatif ne peut donner lieu à annulation de commande, remise sur le prix ou versement de dommages et intérêts. Cette stipulation s'applique sans préjudice des droits du Client consommateur au titre des articles L.216-1 et suivants du Code de la consommation, qui peut résoudre le contrat, après mise en demeure restée infructueuse, en cas de manquement du Prestataire à son obligation d'exécution dans le délai convenu. Les parties s'engagent à respecter les rendez-vous fixés et à s'informer au plus vite de tout impondérable nécessitant un report. Tout changement de projet par le Client peut modifier les délais ; un nouvel échéancier est alors communiqué. Le Prestataire peut modifier les délais en cas de conditions météorologiques défavorables, d'événements extérieurs ou de force majeure.</p>
    <h2>Article 7 – Exécution des prestations (dispositions communes)</h2>
      <p>Le Prestataire peut se déplacer chez le Client afin de réaliser sa Prestation selon la méthode qui lui semble la plus appropriée, à partir des éléments communiqués par le Client et des données constatées sur le terrain. Le Client s'engage à être présent ou représenté aux rendez-vous, à rendre le site accessible et à le sécuriser contre tout accident. Le Prestataire ne saurait être tenu responsable de tout accident ou incident en l'absence d'éléments permettant de sécuriser le lieu d'exécution, avant, pendant et après celle-ci.</p>
      <p>Les observations du Prestataire sont fondées sur les conditions du terrain au jour de l'intervention et ne présagent en rien de leur évolution dans le temps, sauf spécification contraire. Sauf autre modalité demandée, la désignation des arbres et arbustes surnuméraires est réalisée à la griffe forestière ; l'emploi de peinture forestière ou de rubalise biodégradable est facturé au Client.</p>
    <h2>Article 8 – Maîtrise d'œuvre OLD : périmètre et limites</h2>
      <p>Dans le cadre des missions de maîtrise d'œuvre, le Prestataire intervient exclusivement en qualité de maître d'œuvre, au titre d'une prestation purement intellectuelle de conception, d'étude, d'établissement de pièces graphiques et d'assistance. Le Prestataire ne réalise aucuns travaux.</p>
      <p>Périmètre de la mission. La mission de maîtrise d'œuvre est strictement limitée :</p>
      <ul>
        <li>aux travaux de débroussaillement réglementaire, à savoir la coupe d'arbres, d'arbustes et de la strate herbacée ;</li>
        <li>à la conception cartographique d'aménagements d'accès et de défense incendie, notamment aires de retournement, de contournement et de croisement, plateformes et aires de citerne, points d'eau et leurs accès.</li>
      </ul>
      <p>Exclusion expresse des ouvrages d'art. Le Prestataire ne conçoit, ne dimensionne, ne calcule ni ne dirige aucun ouvrage d'art ni aucun ouvrage de génie civil structurel (notamment ponts, ouvrages hydrauliques dimensionnés, murs de soutènement, dallages porteurs, fondations). Toute mission de cette nature relève d'un bureau d'études techniques structure ou d'un ingénieur ouvrage d'art que le Client devra missionner séparément et sous sa propre responsabilité.</p>
      <p>Exécution des travaux par des tiers. L'exécution matérielle des travaux est assurée par une ou plusieurs entreprises de travaux choisies et contractées directement par le Client, agissant sous leur propre responsabilité et leurs propres assurances. Le Client demeure seul maître d'ouvrage. Le Prestataire n'assume aucune responsabilité d'entrepreneur ni aucune garantie légale de construction (notamment garantie de parfait achèvement, garantie biennale ou garantie décennale) au titre de ces travaux.</p>
    <h2>Article 9 – Servitudes DFCI : nature et limites</h2>
      <p>Au titre des servitudes de Défense des Forêts Contre l'Incendie (DFCI), le Prestataire réalise une mission exclusivement intellectuelle d'étude, de relevé et d'établissement des dossiers techniques et cartographiques, selon les référentiels DFCI et le Code forestier en vigueur.</p>
      <p>Absence d'institution de la servitude. Le Prestataire n'institue pas la servitude : sa création, sa modification ou sa suppression relève exclusivement de l'autorité administrative compétente, par acte distinct. Le dossier produit constitue une pièce technique d'aide à la décision destinée à appuyer cette procédure.</p>
      <p>Absence de travaux. Le Prestataire ne réalise aucuns travaux. Les limites définies aux articles 8 et 10 (exécution des travaux par des tiers, dépendance à la qualité des données, précision métrique, absence de valeur juridiquement opposable et recours optionnel au géomètre-expert) s'appliquent de plein droit aux prestations relatives aux servitudes DFCI.</p>
    <h2>Article 10 – Applications de cartographie web : nature, données sources et limites</h2>
      <p>Champ d'application. Le présent article régit les seules Applications de calcul et de représentation cartographique de l'emprise des obligations légales de débroussaillement (ci-après les « Applications de calcul »). Le Module de gestion des OLD et de génération de courriers aux propriétaires fait l'objet de l'article 11.</p>
      <p>Nature. Les Applications déterminent, au moyen d'un algorithme propriétaire de calcul d'équidistance, l'emprise des obligations légales de débroussaillement résultant du croisement des parcelles cadastrales avec les zonages réglementaires (zones urbanisées ou à urbaniser des documents d'urbanisme, PPRIF, porter à connaissance, arrêtés préfectoraux portant l'OLD à 100 mètres, et autres zonages applicables).</p>
      <p>Données sources. Les calculs s'appuient exclusivement sur des données publiques et ouvertes : le plan cadastral de la DGFIP (parcellaire, à l'exclusion du fichier MAJIC et de toute donnée nominative de propriétaire), le bâti de la DGFIP et la BD TOPO de l'IGN.</p>
      <p>Protection des données personnelles. Les Applications de calcul ne mettent en œuvre aucune donnée à caractère personnel : elles ne collectent, ne traitent ni ne restituent aucune information nominative de propriétaire. Le traitement de telles données, lorsqu'il est nécessaire à l'information ou à la mise en demeure des propriétaires, relève exclusivement du Module visé à l'article 11 et du cadre qui y est défini.</p>
      <p>Limites tenant à la donnée. Les résultats sont intégralement conditionnés par la qualité, l'exhaustivité et l'actualité des données publiques utilisées, sur lesquelles le Prestataire n'exerce aucune maîtrise. Le Prestataire décline toute responsabilité quant aux erreurs, omissions, décalages géométriques ou défauts de mise à jour de ces données.</p>
      <p>Précision. Les calculs sont fournis avec une précision métrique, niveau adapté et très largement suffisant pour l'évaluation des emprises de débroussaillement.</p>
      <p>Absence de valeur juridique opposable. Les plans et cartes produits constituent des documents d'aide à la décision et d'information ; ils n'ont aucune valeur juridique opposable et ne sauraient se substituer à un document d'arpentage ou de bornage. Le plan cadastral présentant fréquemment un décalage par rapport au terrain, toute délimitation contradictoire, tout bornage ou tout document d'arpentage relève de la compétence exclusive d'un géomètre-expert.</p>
      <p>Recours optionnel à un géomètre-expert. À la demande du Client, le Prestataire peut solliciter l'intervention d'un géomètre-expert ; cette prestation fait l'objet d'un devis distinct et son coût est susceptible d'excéder celui de la seule prestation de débroussaillement.</p>
    <h2>Article 11 – Module de gestion des OLD et de génération de courriers aux propriétaires : traitement de données à caractère personnel</h2>
      <p>Objet. Le Module de gestion des OLD (ci-après le « Module ») assure le suivi des contrôles et constats de terrain et permet l'édition automatisée de courriers d'information, de recommandation ou de mise en demeure adressés aux propriétaires concernés, sur le fondement des constats de suivi enregistrés. À cette fin, le Module traite un volume très réduit de données : les seules données à caractère personnel sont le nom (ou la dénomination) et l'adresse postale des propriétaires, à l'exclusion de toute autre donnée nominative. Ces données sont associées aux références cadastrales des parcelles et à l'état du constat aux seules fins d'édition du courrier.</p>
      <p>Préparation et non-substitution à l'autorité. Le Module prépare et édite les courriers ; leur signature, leur envoi et, s'agissant des actes relevant de la puissance publique — notamment les mises en demeure —, leur émission demeurent de la seule responsabilité du Client ou de l'autorité compétente. Le Prestataire ne se substitue à aucune décision ni à aucune prérogative de puissance publique.</p>
      <p>Qualité des parties. Le Client — collectivité territoriale, établissement public, gestionnaire de voirie ou tout autre responsable de la mise en œuvre des OLD — détermine les finalités et les moyens du traitement et a la qualité de responsable de traitement au sens de l'article 4 du RGPD. Le Prestataire agit exclusivement pour le compte et sur instruction du Client et a la qualité de sous-traitant au sens de l'article 28 du RGPD.</p>
      <p>Base légale et licéité de la source. Le traitement repose sur le respect d'une obligation légale incombant au Client et sur l'exécution d'une mission d'intérêt public dont il est investi, notamment au titre du Code forestier en matière d'obligations légales de débroussaillement. Le Client garantit qu'il dispose d'un droit d'accès régulier aux données nominatives de propriétaires (notamment issues de la matrice cadastrale) et qu'il est habilité à en confier le traitement au Prestataire. Le Prestataire ne demande ni ne reçoit le fichier MAJIC de la DGFIP, ni aucune base de données nominative étendue : seules les données strictement nécessaires — le nom et l'adresse des propriétaires concernés — lui sont communiquées par le Client, ou collectées sous la responsabilité et sur l'habilitation de ce dernier, conformément au principe de minimisation des données.</p>
      <p>Instructions documentées, confidentialité et sécurité. Le Prestataire ne traite les données que sur instruction documentée du Client, y compris en matière de transfert hors Union européenne, sauf obligation légale contraire à laquelle il serait soumis. Il veille à ce que les personnes autorisées à traiter les données s'engagent au respect de la confidentialité et met en œuvre les mesures techniques et organisationnelles appropriées (article 32 du RGPD) afin de garantir la sécurité, l'intégrité et la confidentialité des données. Les données sont hébergées au sein de l'Union européenne.</p>
      <p>Sous-traitance ultérieure. Le Client autorise le recours à des sous-traitants ultérieurs (notamment hébergeur et, le cas échéant, prestataire d'édition et de routage postal), sous réserve qu'ils présentent des garanties suffisantes et soient liés par des obligations équivalentes. Le Prestataire informe le Client de tout changement projeté et lui permet d'émettre des objections.</p>
      <p>Assistance au responsable de traitement. Le Prestataire assiste le Client, dans la mesure du possible, dans l'exécution de ses obligations : réponse aux demandes d'exercice des droits des personnes concernées, mesures de sécurité, notification des violations de données et réalisation d'une analyse d'impact le cas échéant. Il notifie au Client toute violation de données dans les meilleurs délais après en avoir pris connaissance.</p>
      <p>Durée de conservation et sort des données. Les données ne sont conservées que pour la durée nécessaire aux finalités poursuivies et conformément aux instructions et obligations d'archivage du Client. Au terme de la prestation, le Prestataire restitue les données au Client puis les supprime, ainsi que les copies existantes, sauf obligation de conservation prévue par le droit de l'Union ou le droit national.</p>
      <p>Registre, audit et information des personnes. Le Prestataire tient un registre des activités de traitement effectuées pour le compte du Client et met à sa disposition les informations nécessaires pour démontrer le respect des obligations de l'article 28 du RGPD, en se soumettant aux audits raisonnables diligentés par le Client. L'information des personnes concernées et la mention des voies de recours incombent au Client en sa qualité de responsable de traitement.</p>
      <p>Acte de sous-traitance dédié. Le présent article fixe le cadre de la sous-traitance ; il peut être complété par un accord de traitement des données (DPA) annexé au contrat, qui prévaut en cas de divergence.</p>
    <h2>Article 12 – Études de « Défendabilité » et plans de gestion des OLD</h2>
      <p>Le Prestataire réalise des études d'aléa, de vulnérabilité et de « Défendabilité », des études de voies d'accès et de desserte (PAC) ainsi que des études de défense extérieure contre l'incendie (DECI), hydrants et points d'eau. Il établit également des plans communaux de gestion des OLD comprenant la cartographie du zonage réglementaire, parcelle par parcelle. Ces prestations constituent des missions exclusivement intellectuelles de diagnostic, d'analyse et de préconisation.</p>
      <p>Caractère consultatif. Ces études constituent des avis techniques et des aides à la décision, fondés sur les conditions constatées sur le terrain et les données disponibles à la date de réalisation. Leur mise en œuvre, leur suivi et le contrôle de leur application relèvent du Client, conformément à l'article 14.</p>
      <p>Plans s'appuyant sur les Applications. Lorsque la cartographie du zonage réglementaire ou les plans de gestion des OLD sont produits, en tout ou partie, au moyen des Applications de cartographie web, les limites définies à l'article 10 (dépendance à la qualité des données, précision métrique, absence de valeur juridiquement opposable et recours optionnel au géomètre-expert) s'appliquent de plein droit.</p>
      <p>Absence de travaux. Le Prestataire ne réalise aucuns travaux ni aucune installation au titre de ces prestations.</p>
    <h2>Article 13 – Réglementation</h2>
      <p>Les Prestations respectent les réglementations en vigueur à la date de leur exécution. Dans ses prescriptions, le Prestataire ne peut déroger à ces réglementations. En cas d'oubli ou d'erreur du Prestataire, un avenant est établi dès son signalement par le Client et les modifications inhérentes sont effectuées. En dehors de toute réglementation, le Prestataire assume la pleine responsabilité de sa prescription.</p>
    <h2>Article 14 – Contenu des prestations et sous-traitance</h2>
      <p>Les Prestations sont définies dans le devis accepté par le Client, dont les CGV sont parties intégrantes. Les modifications demandées par le Client peuvent faire l'objet d'un avenant ou d'un nouveau devis en cas de visite supplémentaire ou de nouveaux éléments nécessitant de nouveaux calculs ou études. Le Prestataire peut recourir à la sous-traitance, qui demeure sous son contrôle et sa responsabilité.</p>
      <p>Le rôle du Prestataire n'est pas de vérifier si le Client se conforme à la loi ou s'il a tenu compte des avis émis ; le Client est seul responsable du suivi de l'information. Le Prestataire n'a qu'un rôle de conseil et ne saurait être tenu responsable d'une évolution réglementaire ultérieure à l'acceptation du devis, ni de l'absence de sollicitation d'expertises complémentaires qu'il aurait préconisées.</p>
    <h2>Article 15 – Responsabilités et assurances</h2>
      <p>Le Client est responsable de la sécurité du site étudié et de l'application des préconisations du rapport du Prestataire.   Le Prestataire est titulaire de contrats d'assurance souscrits auprès d'une compagnie notoirement solvable, le garantissant de manière suffisante contre les conséquences pécuniaires de la responsabilité pouvant lui incomber au titre du contrat, pour les domaines d'activités déclarés, dont les garanties principales sont : tous dommages confondus : 8 M€ ; dommages matériels : 3 M€ ; dommages immatériels consécutifs à un dommage matériel ou corporel garanti :  1,5 M€ ; dommages immatériels non consécutifs : 300 k€ ; atteinte à l'environnement : 1,5 M€ ; faute inexcusable de l'employeur : 3 M€.</p>
      <p>Une attestation d'assurance peut être remise au Client sur simple demande. Si le Client estime ces garanties insuffisantes, il doit le déclarer au Prestataire, qui en réfèrera à son assureur ; un nouveau devis intégrant l'éventuelle sur-cotisation sera alors proposé. Toutes les conséquences financières d'une absence de déclaration par le Client de la nécessité de garanties supplémentaires sont intégralement supportées par le Client.</p>
    <h2>Article 16 – Prix</h2>
      <p>Le prix des Prestations est fixé en fonction de la complexité et de la nature de l'opération, de la durée des Prestations et de l'étendue de la mission. Les prix, exprimés en euros, sont fixés dans l'offre, le devis ou le contrat de manière forfaitaire ou unitaire et sont valables trois mois. Les prix s'entendent hors taxes ; le montant des taxes au taux en vigueur lors du règlement s'ajoute aux honoraires. Les éventuels frais de déplacement sont inclus dans les prix proposés.</p>
    <h2>Article 17 – Paiement et délais de règlement</h2>
      <p>À l'acceptation de la commande, le Client verse soit l'intégralité du paiement pour les Prestations d'un montant inférieur à 300,00 € HT, soit un acompte de 50 % pour les montants supérieurs, le solde étant versé au plus tard 45 jours à compter de la date d'émission de la facture. Le paiement s'effectue par espèces (jusqu'à 1 000 €), carte bancaire, PayPal ou virement bancaire, dans le respect de la législation en vigueur. Les Prestations effectuées demeurent la propriété du Prestataire jusqu'au paiement complet. Aucun escompte n'est accordé pour paiement anticipé.</p>
      <p>En cas de retard de paiement, sont exigibles, conformément à l'article L.441-10 du Code de commerce, une indemnité calculée sur la base de 3 fois le taux d'intérêt légal en vigueur appliqué sur le montant TTC impayé, ainsi que, pour les professionnels, une indemnité forfaitaire pour frais de recouvrement de 40,00 € (décret n° 2012-1115 du 2 octobre 2012). Ces sommes sont exigibles de plein droit, sans qu'un rappel soit nécessaire, à défaut de règlement au 45e jour suivant la date d'émission de la facture.</p>
    <h2>Article 18 – Litiges et droit applicable</h2>
      <p>Le présent contrat est soumis au droit français. Le Prestataire ne peut être tenu responsable des dommages, matériels, immatériels ou corporels, résultant d'une mauvaise interprétation des prescriptions des études, comptes rendus ou rapports. En cas de difficulté dans l'application du présent contrat, le Client s'adresse prioritairement au Prestataire pour rechercher une solution amiable. Les réclamations sont reçues avec bienveillance, la bonne foi étant présumée. À défaut de solution amiable, et après médiation le cas échéant : entre professionnels commerçants, le tribunal de commerce de Toulon est seul compétent, y compris en cas de référé, d'appel en garantie ou de pluralité de défendeurs ; le Client consommateur peut saisir la juridiction compétente dans les conditions de droit commun ; les litiges relatifs aux contrats de la commande publique relèvent des juridictions et des règles qui leur sont propres.</p>
    <h2>Article 19 – Médiation de la consommation</h2>
      <p>Conformément à l'article L.612-1 du Code de la consommation, le Client consommateur a le droit de recourir gratuitement au service de médiation proposé par le Prestataire. Le médiateur de la consommation est CM2C, joignable par voie électronique (www.cm2c.net) ou postale : CM2C, 49 rue de Ponthieu, 75008 Paris.</p>
    <h2>Article 20 – Données personnelles, RGPD et confidentialité</h2>
      <p>Les données personnelles collectées par le Prestataire sont enregistrées dans son fichier clients. Les informations collectées sont strictement nécessaires à la bonne gestion des relations et des commandes. Le Prestataire s'engage à ne pas communiquer les coordonnées de ses Clients et à garder confidentielles les informations qui lui sont transmises. La durée de conservation des données de prospect n'ayant pas commandé est de deux ans ; celle des données client est de six ans, du fait de la réglementation fiscale sur la facturation.</p>
      <p>Le consentement n'est pas requis lorsque les données sont collectées pour l'exécution d'un contrat ou de mesures précontractuelles (article 6 du RGPD). Le Prestataire met en œuvre un traitement de données personnelles ayant pour finalité la vente et la livraison des produits et services définis au présent contrat. La référente protection des données est Madame Diana Jeannot, Présidente ; le Prestataire n'a pas désigné de délégué à la protection des données au sens de l'article 37 du RGPD, cette désignation n'étant pas obligatoire au regard de ses activités. Le Client peut, sous réserve d'un justificatif d'identité valide, exercer ses droits auprès d'elle par courrier recommandé au siège ou par courrier électronique à contact@pyrovigil.fr.</p>
      <p>Applications de cartographie web. Conformément à l'article 10, les Applications n'exploitent que des données publiques non nominatives et ne mettent en œuvre aucun traitement de données à caractère personnel relatif aux propriétaires des parcelles. Néanmoins, le Module de gestion des OLD, qui édite des courriers nominatifs aux propriétaires, traite en revanche des données à caractère personnel limitées au nom et à l'adresse des propriétaires ;               ce traitement s'effectue exclusivement dans le cadre défini à l'article 11, le Prestataire y agissant en qualité de sous-traitant du Client responsable de traitement.</p>
    <h2>Article 21 – Propriété intellectuelle</h2>
      <p>Le Prestataire est seul titulaire des droits de propriété intellectuelle de l'ensemble des Services proposés. L'ensemble des contenus et supports, quelle qu'en soit la forme (papier, électronique, numérique, orale), demeure sa propriété exclusive et ne peut faire l'objet d'aucune utilisation, transformation, reproduction ou exploitation non expressément autorisée. En contrepartie du paiement du prix, les contenus transmis font l'objet d'un droit d'utilisation personnel, non cessible et non exclusif, pour la seule activité du Client. Le Client s'interdit, sauf autorisation écrite, d'utiliser à d'autres fins, de reproduire ou de diffuser les études, documentations, outils, méthodes et savoir-faire du Prestataire.</p>
      <p>Applications et algorithmes. Les Applications, leur code source, leurs interfaces et leur algorithme de calcul d'équidistance constituent des actifs de propriété intellectuelle exclusifs et confidentiels du Prestataire. L'accès ou l'utilisation d'une Application confère au Client une licence d'utilisation personnelle, non exclusive, non cessible et limitée à la durée et au périmètre du contrat, à l'exclusion de tout droit de reproduction, décompilation, rétro-ingénierie, extraction substantielle de données, revente ou mise à disposition de tiers.</p>
      <p>Annexe – Modèle de formulaire de rétractation</p>
      <p>(Veuillez compléter et renvoyer le présent formulaire uniquement si vous souhaitez vous rétracter du contrat.)</p>
      <p>À l'attention de PYROVIGIL – 49, rue des Tournesols, 83260 La Crau – contact@pyrovigil.fr</p>
      <p>Je / nous (*) vous notifie / notifions (*) par la présente ma / notre (*) rétractation du contrat portant sur la vente du bien (*) / pour la prestation de services (*) ci-dessous :</p>
      <p>Commandé le (*) / reçu le (*) :</p>
      <p>Nom du (des) consommateur(s) :</p>
      <p>Adresse du (des) consommateur(s) :</p>
      <p>Signature du (des) consommateur(s) (uniquement en cas de notification sur papier) :</p>
      <p>Date :</p>
      <p>(*) Rayez la mention inutile.</p>
      <p>—————————————————————————————————————</p>
      <p>A la CRAU, le 2 juillet 2026</p>
      <p>Diana JEANNOT, présidente de la SAS PYROVIGIL</p>
  </LegalPage>
</template>
